### PR TITLE
ERD rev.3 - field relations in labels

### PR DESCRIPTION
**Pull request by Murphy812**
Task's name:
[ISSUE-343]: Create Entity-Relationship Diagram (ERD)
[ISSUE-346]: Create component diagram

Developer's full name:
 Alexander Chuprin 

Link to PR:
https://github.com/Sunagatov/Iced-Latte/pull/312

Changes:
- ERD: field relations are in labels now
- Component diagram: created

### CODE REVIEW

**Comment by ilsinyakov** [comment]
Hello, @Murphy812   
ERD.png  
Why do entities: **orders, order_item, payment, shopping_cart, shopping_cart_item, reservation** not have relationships?

**Comment by Murphy812** [comment]
> Hello, @Murphy812 ERD.png Why do entities: **orders, order_item, payment, shopping_cart, shopping_cart_item, reservation** not have relationships?

Because right now ERD reflects the actual situation in the code

**Review by TetianaPerinha — APPROVED** [review]
Approved

**Review by ilsinyakov — APPROVED** [review]
Approved

**Review by Sunagatov — APPROVED** [review]

**Pull request merged**
